Elastic pagination
TeskaLabs/asab pull request #130
Opened 2020-10-26 09:04 UTC by kanospet

2020-10-26 17:11 UTC, ateska requested changes

2020-10-26 17:11 UTC, ateska commented on asab/storage/elasticsearch.py
> +	async def get_total_count(self, index):
`count()`

2020-10-27 09:59 UTC, ateska approved these changes

2020-10-27 10:22 UTC, PremyslCerny approved these changes

2020-10-27 10:26 UTC, merged