Add RBAC decorator with an example.
TeskaLabs/asab pull request #142
Opened 2021-02-17 09:19 UTC by PremyslCerny

2021-02-17 09:19 UTC, PremyslCerny commented
@ateska This is a first attemp to add RBAC decorator as part of authorization. Please see.

2021-02-17 11:35 UTC, ateska requested changes
Major remark regarding the structure of the `authz` handler decorator.

2021-02-17 11:35 UTC, ateska commented on examples/web-authz-rbac.py
> +	@asab.web.authz.authz_rbac_tenant
`@asab.web.authz.required("tenant.access")`

`tenant.access` is a name of resource (a role contains a list of resources that it grants access to).
`required()` call can take more than one resource name.

2021-02-17 15:12 UTC, PremyslCerny commented
@ateska Major remark implemented.

2021-02-17 17:12 UTC, ateska requested changes

2021-02-17 17:12 UTC, ateska commented on asab/web/authz/decorator.py
> +def required(*operations):
`required(*resources):`

2021-02-17 17:12 UTC, ateska commented on asab/web/authz/decorator.py
> +		# TODO: Implement more RBAC operations
What?

2021-02-18 08:10 UTC, PremyslCerny commented on asab/web/authz/decorator.py
> +def required(*operations):
This is already resolved.

2021-02-18 08:10 UTC, PremyslCerny commented on asab/web/authz/decorator.py
> +		# TODO: Implement more RBAC operations
Sorry, leftover.

2021-02-18 08:10 UTC, PremyslCerny commented
@ateska Leftover removed.

2021-02-18 08:24 UTC, ateska requested changes

2021-02-18 08:24 UTC, ateska commented on asab/web/authz/decorator.py
> +			for resource in resources:
This has to be cached in some reasonable way.
Ideally using some kind of credentials session indicator in the HTTP request.

But for a starter, ~5 minute cache and TODO will be ok

2021-02-18 11:16 UTC, PremyslCerny commented
@ateska Simple cache added. Please review.

2021-02-18 21:59 UTC, ateska requested changes

2021-02-19 10:48 UTC, PremyslCerny commented
@ateska Like this? :D

2021-02-19 12:21 UTC, ateska requested changes
Not there yet

2021-02-19 12:21 UTC, ateska commented on asab/web/authz/service.py
> +		self.RequiredDecoratorCache = {}
`self.Cache = {}`

2021-02-19 12:21 UTC, ateska commented on asab/web/authz/decorator.py
> +				authorized = authz_service.get_from_required_decorator_cache(cache_key)
The cache mechanism HAS TO be completely encapsulated in the service.
The service should provide the method, that takes input "resources , tenant_id" and do the autorization in it.
The name of the method is obviously `authorize(...)`

2021-02-19 12:55 UTC, PremyslCerny commented
@ateska Logic is now in the authorize method. Please see again.

2021-02-19 16:08 UTC, ateska requested changes

2021-02-19 16:08 UTC, ateska commented on asab/web/authz/decorator.py
> +
```
authz_service.authorize(
    resources=resources,
    access_token=request.headers.get(aiohttp.hdrs.AUTHORIZATION, None),
    tenant=None if not hasattr(request, "Tenant") else request.Tenant
)
```

2021-02-19 16:08 UTC, ateska commented on asab/web/authz/service.py
> +			if authorized is not None:
```
if authorized is not None:
    return authorized
```

2021-02-19 16:08 UTC, ateska commented on asab/web/authz/service.py
> +		for resource in resources:
Don't do this here.

```
resources = ','.join(sorted(resources))
```

2021-02-19 16:23 UTC, PremyslCerny commented
@ateska Remarks implemented. Another round, pls. :)

2021-02-19 19:46 UTC, ateska requested changes

2021-02-19 19:46 UTC, ateska commented on asab/web/authz/decorator.py
> +
In order to be really hacker-resistant here, I suggest to add explicit test here:

```
if access_token is None:
    raise aiohttp.web.HTTPUnauthorized()
```

2021-02-19 19:46 UTC, ateska commented on asab/web/authz/service.py
> +		return True
```
return False
```

... you want to be pessimistic when it comes to authorization.

2021-02-19 19:46 UTC, ateska commented on asab/web/authz/service.py
> +				if not authorized:
```
if authorized:
    return True
```

Since you want to be strict on returning True here.

2021-02-19 19:46 UTC, ateska commented on asab/web/authz/service.py
> +				authorized = resp.status == 200
Also check the actual content of the response.

2021-02-22 08:45 UTC, PremyslCerny commented
@ateska Remarks implemented. Another round please. ;-)

2021-02-22 12:08 UTC, ateska requested changes
Provided.

2021-02-22 12:08 UTC, ateska commented on asab/web/authz/decorator.py
> +				tenant=None if not hasattr(request, "Tenant") else request.Tenant,
`tenant = getattr(request, "Tenant", None)`

2021-02-22 12:08 UTC, ateska commented on asab/web/authz/decorator.py
> +			if not await authz_service.authorize(
`if await authz_service.authorize`

2021-02-22 12:08 UTC, ateska commented on asab/web/authz/decorator.py
> +				raise aiohttp.web.HTTPUnauthorized()
Return here ... and only here ... everywhere else `raise aiohttp.web.HTTPUnauthorized()`

2021-02-22 12:37 UTC, PremyslCerny commented
@ateska Updated. Please see again.

2021-02-22 15:53 UTC, ateska approved these changes

2021-02-22 16:05 UTC, merged