[WIP] Feature/asab library
TeskaLabs/asab pull request #212
Opened 2022-05-05 09:38 UTC by bochkver

2022-05-05 12:17 UTC, PremyslCerny commented on asab/library/providers/zookeeper.py
> +class ZooKeeperLibraryProvider(LibraryProviderABC):
@bochkver Make sure you are synchronized with Mithun here. The provider will be used by all services and based on Kazoo.

2022-05-05 12:18 UTC, PremyslCerny commented on asab/library/providers/filesystem.py
> +		self.LibraryBaseDir = path
@bochkver Test it with both relative and absolute paths.

2022-05-05 12:18 UTC, PremyslCerny commented on asab/library/__init__.py
> +		L.info("Sample module finalized.")
@bochkver Please make sure you remove these sample logs. :)

2022-05-05 13:17 UTC, ateska commented on asab/library/providers/abc.py
> +	async def write(self, path, data):
No `write` in the ASAB, it is read-only provider.

2022-05-19 20:03 UTC, ateska requested changes

2022-05-19 20:03 UTC, ateska commented on asab/library/__init__.py
> +		app.PubSub.subscribe_all(self)
This is not needed - there is no subscription.

2022-05-19 20:03 UTC, ateska commented on asab/library/providers/zookeeper.py
> +		)
Please rebase to https://github.com/TeskaLabs/asab/pull/213 and test that.
Here you need to use `ZooKeeperService.build_container(...)`, don't construct the container on your own.

2022-05-19 20:03 UTC, ateska commented on asab/library/providers/zookeeper.py
> +		await self.ZookeeperContainer.initialize(app)
You don't need to do this explicitly.

2022-05-23 20:34 UTC, ateska requested changes

2022-05-23 20:34 UTC, ateska commented on asab/library/providers/__init__.py
> +	"ZooKeeperLibraryProvider",
You don't need to export anything here.

2022-05-23 20:34 UTC, ateska commented on asab/library/service.py
> +		app.PubSub.subscribe_all(self)
You don't need to subscribe b/c there is no PubSub annotation used here.

2022-05-25 14:12 UTC, ateska requested changes

2022-05-27 15:25 UTC, ateska approved these changes

2022-05-30 07:09 UTC, merged