Add a simple gauge metrics for memory used.
TeskaLabs/asab pull request #216
Opened 2022-05-23 09:44 UTC by PremyslCerny

2022-05-23 09:45 UTC, PremyslCerny commented
@ateska Please see. Any suggestions are welcome.

2022-05-23 20:26 UTC, ateska requested changes

2022-05-23 20:26 UTC, ateska commented on asab/metrics/service.py
> +import psutil
This is the external dependency. I would like to try it without it - you can basically read that from `/proc/self` file system AFAIK.

2022-05-23 21:26 UTC, ateska requested changes

2022-05-23 21:26 UTC, ateska commented on asab/metrics/service.py
> +				"memory.used": self.Process.memory_info().rss,
The metric name should be consistent with Linux memory/swap naming.

2022-05-25 07:21 UTC, ateska requested changes

2022-05-25 07:21 UTC, ateska commented on asab/metrics/service.py
> +			"asab.memory",
Status information about the OS process.

2022-05-25 07:21 UTC, ateska commented on asab/metrics/service.py
> +				"help": "Memory consumed by the process.",
This is not only a memory consumption ...

2022-05-25 09:10 UTC, pagan-coder approved these changes

2022-05-25 12:58 UTC, ateska requested changes

2022-05-25 12:58 UTC, ateska commented on asab/metrics/service.py
> +			"asab.process",
Don't say asab, please. It is `os.stat` for example.

2022-05-26 07:46 UTC, ateska commented
Can I see the output of this metrics, please? 

:-)

2022-05-26 08:27 UTC, PremyslCerny commented
@ateska Of course, they are key value pairs:

```
VmPeak 184795136
VmSize 118030336
VmLck 0
VmPin 0
VmHWM 29437952
VmRSS 29437952
VmData 27840512
VmStk 135168
VmExe 2707456
VmLib 5586944
VmPTE 114688
VmSwap 0
```

2022-05-26 09:23 UTC, ateska commented
Nice.

2022-05-26 09:43 UTC, merged