Allow multiple storage services
TeskaLabs/asab pull request #258
Opened 2022-07-12 08:05 UTC by Plesoun

Warning, this may impact multiple existing services as the service names needed to be distinguised based on the type.
Example config:
[asab:storage]
type=elasticsearch,mongodb

2022-07-12 09:18 UTC, mithunbharadwaj commented on asab/storage/__init__.py
>  		sttype = asab.Config.get('asab:storage', 'type')
'type' is list.

2022-07-12 13:35 UTC, ateska requested changes
This doesn't seems to be a good idea.
`self.Service` is abstraction that hides implementation detail.

This MR goes against this.
Why it is needed? It seems an incomplete/wrong design direction.

2022-07-12 14:16 UTC, Plesoun commented
> This MR doesn't seems to be a good idea. `self.Service` is abstraction that hides implementation detail.
> 
> This MR goes against this. Why it is needed? It seems an incomplete/wrong design direction.

As it is now, a single asab application can only have a single storage service. If your app has a need for (for example) ES and Mongo provider you cannot do that. Is it wrong for an asab application to have storage service for both?

2022-07-12 21:56 UTC, ateska commented
> > This MR doesn't seems to be a good idea. `self.Service` is abstraction that hides implementation detail.
> > This MR goes against this. Why it is needed? It seems an incomplete/wrong design direction.
> 
> As it is now, a single asab application can only have a single storage service. If your app has a need for (for example) ES and Mongo provider you cannot do that. Is it wrong for an asab application to have storage service for both?

You should be able to spin multiple storage services ... that the way forward here.

2022-07-13 16:00 UTC, mithunbharadwaj commented
@ateska I don't think it's possible due to this condition

https://github.com/TeskaLabs/asab/blob/master/asab/application.py#L426


asab.StorageService is already registered with elasticsearch first for instance.

2022-07-14 11:41 UTC, closed without merging