Improved logging
TeskaLabs/asab pull request #264
Opened 2022-07-20 18:22 UTC by bochkver

Improved logging in -v mode that provides info about where each library provider is connected 
https://github.com/TeskaLabs/asab/issues/254

2022-07-21 17:20 UTC, ateska requested changes
Better to use structured data.

Also @eliska-n was the primary requestor of this, so she could provide more (and faster) feed back.

2022-07-21 17:20 UTC, ateska commented on asab/library/providers/azurestorage.py
> +		L.info("AzureStorage library provider {} is connected.".format(self.Path))
```
L.info("Connected.", struct_data={'path':self.Path})
```

2022-07-22 09:47 UTC, eliska-n commented
yes, when debugging I would like to be ensured that the provider connects where I want. (Where I think my configuration targets.)
In the best scenario I would like to see something like that:
`ZooKeeper library provider connected to: 'zk://servername:2181/some/subpath' `

2022-07-22 09:53 UTC, eliska-n commented
Or using the `struct_data`... I don't care. But I think the user/developer/me/whoeverelse would like to see the full URL to be really sure that the provider is looking into the right node. Noone wants to go through the code and seek for the explanation of the `path` or `self.Path`.

2022-08-17 07:10 UTC, ateska approved these changes

2022-08-17 08:11 UTC, eliska-n approved these changes

2022-08-17 09:15 UTC, merged