Enhancement : read disabled on tick
TeskaLabs/asab pull request #271
Opened 2022-07-26 16:23 UTC by mithunbharadwaj

2022-07-29 07:42 UTC, ateska requested changes

2022-07-29 07:42 UTC, ateska commented on asab/library/service.py
> +		app.PubSub.subscribe("Application.tick!", self.on_tick)
This is too often - must be done e.g. once per minute.

2022-07-29 11:08 UTC, mithunbharadwaj commented
@ateska does it make sense to make read_disabled() blocking code?
https://github.com/TeskaLabs/asab/blob/master/asab/library/service.py#L122

2022-07-31 12:58 UTC, ateska approved these changes

2022-08-03 08:26 UTC, merged