WIP: Websocket example
TeskaLabs/asab pull request #281
Opened 2022-08-12 15:12 UTC by eliska-n

2022-08-15 09:05 UTC, ateska requested changes

2022-08-15 09:05 UTC, ateska commented on examples/websocket_server.py
> +		web_app.router.add_get("/rc", self.rc)
`/rc` is likely too off-context here.

2022-08-15 09:22 UTC, eliska-n commented on examples/websocket_server.py
> +		self.WS = None
Yes, creating a WS container in asab has been in my backlog for a while... :(

2022-08-23 15:51 UTC, eliska-n commented
@ateska 
I have a task to send continuously state of a long-running subprocess (docker compose up). But I didn't know how to send it to UI. And I thought that WebSocket would probably be the choice even for UI. But as we have already discussed, WebSockets with various purposes should be somehow separated, and it would be nice to have a service in asab that would help me to handle this. And as this pull request has already been open but somehow useless, I decided to give it a bigger role. 
I have doubts about the code, but I would like to open the discussion.

2022-08-24 21:32 UTC, ateska commented
Ha!
This is brave ;-)

2022-08-24 22:41 UTC, ateska requested changes
We will need to elaborate on this a bit ...

2022-08-24 22:41 UTC, ateska commented on asab/web/ws/container.py
> +		self.Messages = list()
Meh, that's not a good idea :-/

2022-08-29 15:39 UTC, eliska-n commented
I fixed the `get()` method and added `send_json_all()`. And I like it.

2022-08-29 17:44 UTC, ateska approved these changes
Ok. So let's merge it ;-)

2022-08-30 08:57 UTC, merged