Bug: Library fails to list items
TeskaLabs/asab pull request #342
Opened 2023-02-14 03:40 UTC by mithunbharadwaj

2023-02-14 10:34 UTC, ateska requested changes

2023-02-16 04:47 UTC, mithunbharadwaj commented on asab/library/service.py
> +		else:
@ateska Instead of 

```
while path[-1:] == '/':
	path = path[:-1]
```
	
we can just do this ?
`path = path.rstrip('/')`

2023-02-21 12:28 UTC, ateska commented on asab/library/service.py
> +		else:
This whole bit is wrong, `os.path.splitext` doesn't make any sense, a "directory" path (for listing) has no extension and you should do that.

I propose simple `assert(path[-1:]) == '/'` here to enforce "directory" paths ends with `/`.

2023-02-22 07:51 UTC, mithunbharadwaj commented on asab/library/service.py
> +		else:
@ateska I agree, It was rather simple solution!

2023-02-22 08:29 UTC, ateska commented
Can you please add nice comments to ALL asserts here?
It will help dependant services resp. people to fix what will need to be fixed.

E.g.:

`assert(path[-1:]) == '/', "Directory path must end with "/"` ... not sure about the syntax

2023-02-22 11:30 UTC, mithunbharadwaj commented on asab/library/service.py
> +		else:
@ateska Can be merged?

2023-02-22 15:06 UTC, ateska approved these changes

2023-02-23 04:18 UTC, merged