Corrected logic of watch_metrics endpoint
TeskaLabs/asab pull request #345
Opened 2023-02-17 11:06 UTC by language-shprt

1) Corrected a typo in the Examples section (wrong endpoint name, reversed);
2) The full metrics table (including web_requests metrics) is shown only if they have been explicitly asked for (the relevant parameter web_requests_metrics is True).
3) Corrected the logic behind tags parameter (returned tags for any string in the request, including False).

2023-02-20 09:53 UTC, eliska-n approved these changes

2023-02-20 11:02 UTC, ateska requested changes
Discussed, rework is needed ;-)

2023-02-21 22:45 UTC, ateska requested changes
Small change needed, then mergeable.

2023-02-21 22:45 UTC, ateska commented on asab/metrics/web_handler.py
> +		filter = request.query.get("f")
`filter` instead of `f`

2023-02-22 15:07 UTC, ateska approved these changes

2023-02-22 15:09 UTC, eliska-n approved these changes

2023-02-22 15:10 UTC, merged