Initialization of web requests metrics based on configuration
TeskaLabs/asab pull request #349
Opened 2023-02-20 15:17 UTC by language-shprt

2023-02-23 09:31 UTC, eliska-n approved these changes

2023-02-24 09:28 UTC, ateska requested changes

2023-02-24 09:28 UTC, ateska commented on asab/config.py
> +			"web_requests_metrics": False,
Comment please.

2023-02-24 11:13 UTC, language-shprt commented on asab/config.py
> +			"web_requests_metrics": False,
+

2023-02-24 12:53 UTC, ateska approved these changes

2023-02-24 14:04 UTC, merged