Metrics: Feature/correct timestamp
TeskaLabs/asab pull request #358
Opened 2023-02-28 16:10 UTC by language-shprt

2023-02-28 20:28 UTC, eliska-n requested changes
Please proceed with the Influx target. :superhero:

2023-02-28 20:28 UTC, eliska-n commented on asab/metrics/service.py
> +	def create_gauge(self, metric_name, app, tags=None, init_values=None, help=None, unit=None):
It is already solved on line 102. I didn't remember that at all. :see_no_evil:

2023-02-28 20:28 UTC, eliska-n commented on examples/metrics.py
> +		self.MyGauge = metrics_service.create_gauge("mygauge", self, tags={'foo': 'bar'}, init_values={'v1': 0, 'v2': 0})
please keep the example as i was in the end

2023-02-28 20:28 UTC, eliska-n commented on asab/metrics/metrics.py
> +			"measured@": self.app.time()
self.App.time()

2023-03-02 11:17 UTC, eliska-n commented on asab/metrics/metrics.py
> +		self._field = field
This is not nice. @ateska, we will need to untangle this

2023-03-06 21:47 UTC, eliska-n commented
- I moved all necessary from __init__.py of the metrics test to the baseclass. There was a teardown method missing.
- I wanted to remove the mock `_flush_metrics` method of the `MockMetricsService`, but I found it reasonable in the end. However, I changed the time of the flush, so you can also distinguish in the test between the time of `metric.App.time()` and `now` from the "flush". 
- I started with the Counter with Dynamic Tags, so you can take it as an example and continue with these other metrics with dynamic tags
- The tests for EPS Counter and DutyCycle are not very exhausting, maybe it will be easier to make some more now. Tests for other histogram with dynamics tags are missing

2023-03-06 22:12 UTC, eliska-n requested changes

2023-03-06 22:12 UTC, eliska-n commented on asab/metrics/influxdb.py
> +			timestamp = now
As I understand it now... "measured@" should always be in the field, right? If it is not, something is wrong...?

2023-03-14 09:55 UTC, ateska requested changes
Please, also update the documentation.

2023-03-14 09:55 UTC, ateska commented on asab/metrics/influxdb.py
> +	if "measured@" in field:
Rename to `measured_at`

2023-03-14 09:55 UTC, ateska commented on test/test_metrics/baseclass.py
> +class MockApplication(object):
Remove use of `.Loop` from the`DutyCycle`, replace by `.App` ... so that it is unified with the rest of ASAB.

2023-03-14 09:55 UTC, ateska commented on test/test_metrics/baseclass.py
> +class MockMetricsService(MetricsService):
Please provide comments for "why these Mock classes are needed"

2023-03-14 09:55 UTC, ateska commented on asab/metrics/web_handler.py
> +			timestamp = time.strftime("%Y-%m-%d %H:%M:%S", timestamp)
Add a milliseconds, align with `asab.log` format.

2023-03-14 09:55 UTC, ateska commented on asab/metrics/web_handler.py
> +import time
Remove lines 28..31 ... they are obsolete.

2023-03-17 08:56 UTC, ateska approved these changes
One comment but that could be solved in separate MR.

2023-03-17 08:56 UTC, ateska commented on test/test_metrics/baseclass.py
> +class MockApplication(object):
Yes, please change that.
Duty cycle is used only in BSPump, so please coordinate with @PremyslCerny and do the change in the separate MR.

2023-03-24 15:43 UTC, merged