Documentation/asab storage
TeskaLabs/asab pull request #379
Opened 2023-03-20 16:41 UTC by mejroslav

A first attempt to create a documentation for `asab.storage`.

![Screenshot 2023-03-20 at 17-40-18 Storage — ASAB documentation](https://user-images.githubusercontent.com/68327081/226408835-0258fd63-e812-4a45-992f-9bbb7e6c8c2d.png)

2023-03-21 16:37 UTC, eliska-n requested changes

2023-03-21 16:37 UTC, eliska-n commented on doc/asab/storage.rst
> +Although these three databases are different, accessing the database and manipulation with collections is done by using the same methods.
I think this si called strategy pattern. Maybe I am wrong... It is not important for the documentation, you can try to google it :) Architecture patterns bring a lot of fun also.

Storage Service provides a unified interface for accessing and manipulating collections across multiple database technologies.

2023-03-21 16:37 UTC, eliska-n commented on doc/asab/storage.rst
> +For accessing the storage, simply `add asab.storage.Module`` when initializing and register the service.
It is subjective what is "simple". But it is ok here, we don't need to be 100% official.

2023-03-21 16:37 UTC, eliska-n commented on doc/asab/storage.rst
> +Upsertors are used for manipulations with databases. Upsertor is an object that works like a pointer to the specified database and optionally to object id.
The whole Storage Service is used to manipulate with database. First sentence says nothing new.

![image](https://user-images.githubusercontent.com/82450969/226674826-82d606b6-2c22-42bf-8f47-ae715ba552d6.png)
I know it is not 100% true for this implementation, but it is one clear sentence on what "upsert" mean

2023-03-21 16:37 UTC, eliska-n commented on doc/asab/storage.rst
> +The method :func:`upsertor()` create an upsertor object associated with the specified collection. It takes `collection` as an argument and can have two parameters `obj_id` and `version`, which are us
The `upsertor()` method creates... *in English* (use Grammarly at least - it is available as VSCode plugin, pro is available at TL)
Metoda `upsertor()` vytváří... *v češtině*

2023-03-21 16:37 UTC, eliska-n commented on doc/asab/storage.rst
> +    object_id = await u.execute()
reference doccs for Upsertor that would clearly show it is coroutine is missing...?

2023-03-21 16:37 UTC, eliska-n commented on doc/asab/storage.rst
> +When the requested object is not found in the collection, the method raises ``KeyError``. Remember to handle this exception properly when using databases in your services and prevent them from crashi
That's so sweet :slightly_smiling_face:

2023-03-21 17:19 UTC, ateska commented on doc/asab/storage.rst
> +ASAB provides a service for storing data. Data can be stored in memory or in dedicated document database. For now, `MongoDB <https://www.mongodb.com/>`_ and `Elastic Search <https://www.elastic.co/>`
;-)

2023-03-21 17:22 UTC, ateska requested changes

2023-03-21 17:22 UTC, ateska commented on doc/asab/storage.rst
> +Storing data in Elastic Search
"ElasticSearch"

2023-03-23 19:09 UTC, mejroslav commented
I think I've reached the point where I'm satisfied with what I've done. The user should now have a good understanding of how to interact with databases, how to encrypt and decrypt data, has access to the reference, where (s)he can look at the provided methods, and he can easily find the examples that are descriptive enough (from my point of view).

2023-03-23 21:33 UTC, ateska approved these changes

2023-03-27 08:51 UTC, merged