New auth middleware and decorator
TeskaLabs/asab pull request #395
Opened 2023-04-03 17:26 UTC by byewokko

2023-04-25 15:03 UTC, ateska requested changes

2023-04-26 10:16 UTC, byewokko commented on asab/web/auth/decorator.py
> +def require_superuser(handler):
removed

2023-04-26 10:16 UTC, byewokko commented on asab/web/auth/__init__.py
> +	"no_auth",
renamed

2023-04-27 14:33 UTC, eliska-n commented
bsquery tenant-aware option without resources
dev mode seems not to work...
or do I need to mock user info?

```
[auth]
dev_mode=yes
```

```
class BSQueryApp(asab.Application):

	def __init__(self):
		super().__init__()

		self.add_module(asab.web.Module)
		self.add_module(asab.zookeeper.Module)
		self.add_module(asab.metrics.Module)

		self.ASABApiService = asab.api.ApiService(self)

		# Initialize web container
		self.add_module(asab.web.Module)
		self.WebService = self.get_service("asab.WebService")
		self.WebContainer = asab.web.WebContainer(self.WebService, "web")

		# Initialize authorization
		self.AuthService = asab.web.auth.AuthService(self)
		self.WebContainer.WebApp.middlewares.append(asab.web.rest.JsonExceptionMiddleware)
		self.AuthService.install(self.WebContainer)
		...
```

asab.web.auth.service No Authorization header.

2023-04-27 14:50 UTC, byewokko commented on asab/web/auth/service.py
> +		"dev_user_info_path": "",
@eliska-n (I can't reply directly to your comment)
Yes, the dev mode works by injecting mock userinfo to every request. If you want to access everything, you need to overwrite the default userinfo by providing your own superuser userinfo file. 
You specify `dev_user_info_path=/path/to/userinfo.json` and inside that file just put
```json
{
 "resources": {
  "*": ["authz:superuser"],
  "my-tenant": ["authz:superuser"],
  "another-tenant": ["authz:superuser"],
 }
}
```

2023-04-28 08:12 UTC, byewokko commented on asab/web/auth/service.py
> +		"dev_user_info_path": "",
Now that I think about it, I'll add the superuser resource to the default userinfo. That will be the most common usage anyways.

2023-05-03 13:25 UTC, merged