Feature: Library logs history
TeskaLabs/asab pull request #429
Opened 2023-06-01 14:36 UTC by mithunbharadwaj

2023-06-13 10:01 UTC, ateska requested changes
I assume that the write history function will follow.

2023-06-13 10:01 UTC, ateska commented on asab/library/service.py
> +		self.History = []
Don't store history in the microservice, always load that fresh.

2023-06-13 10:02 UTC, ateska commented
Oh, this whole functionality needs to be in the `asap-library` not here.

2023-07-10 17:46 UTC, ateska commented
Will this be closed? @mithunbharadwaj

2023-07-11 08:47 UTC, mithunbharadwaj commented
Closing MR, Solved the problem in Microservice.

2023-07-11 08:47 UTC, closed without merging