Fix: Subscribe to changes in library - gitprovider
TeskaLabs/asab pull request #432
Opened 2023-06-12 16:14 UTC by eliska-n

- PubSub messages cannot be sent from different thread (proactor)
- I removed other ways of authorization - I left only deploy key possibility as this is the only one functional and actively used.

2023-06-12 18:08 UTC, ateska requested changes
Methods that are to be called from the proactor has to be private (or in-line functions).

`def _do_pull(..)` instead of `def pull()`

2023-06-12 18:12 UTC, ateska requested changes
Subscribe to `/` is equal to any other subscribe.
You don't need to  (must not) handle that differently.

See this:
```
if path == "/":
	to_publish.append(path)
elif ("/" + i.old_file.path).startswith(path):
	to_publish.append(path)
```

2023-06-12 20:48 UTC, ateska approved these changes

2023-06-13 08:28 UTC, mejroslav approved these changes
It works!

2023-06-13 09:00 UTC, merged