Add API Key authorization option for ElasticSearch
TeskaLabs/asab pull request #441
Opened 2023-07-03 15:53 UTC by mejroslav

2023-07-10 10:52 UTC, language-shprt commented on asab/storage/elasticsearch.py
> +				raise ConnectionError("Both username and API key specified. Please choose one option. {}".format(err))
Should it be specifically a ConnectionError? If so, do we want to consider the possibility of changing the comment "Both username and API key specified..."?

2023-07-10 11:12 UTC, language-shprt commented on asab/storage/elasticsearch.py
>  		return self._ClientSession
`auth=self._auth` will be always None with api_key... Do we want to update this given that we are adding api_key as a second authorization method?

2023-07-10 11:12 UTC, language-shprt commented on asab/storage/elasticsearch.py
> +
Won't it just return False after encountering a faulty node? It won't go further (won't check the rest of the urls).

2023-07-10 11:12 UTC, language-shprt commented on asab/storage/elasticsearch.py
If urls from configs are parsed, checked and corrected properly (namely "/" is added at the end), we don't need this condition. If not - don't we need to have it at every endpoint?

2023-07-10 11:12 UTC, language-shprt commented on asab/storage/elasticsearch.py
> +
In the StorgeService we created default ssl context as `self.SSLcontext = ssl.create_default_context(cafile=ssl_ca_file)`, where `ssl_ca_file `was a configuration item.

Here `self.Storage.SSLcontext` is used for a certificate path.

2023-07-10 17:49 UTC, ateska requested changes

2023-07-10 17:49 UTC, ateska commented on asab/storage/elasticsearch.py
> +			'elasticsearch_ssl_ca_file': '',
just `elasticsearch_ca_file` please.

2023-07-11 13:07 UTC, language-shprt commented on asab/storage/elasticsearch.py
> +				) as resp:
Do we need Headers here as well? So that we can delete things with api_key?

2023-07-11 13:27 UTC, language-shprt commented on asab/storage/elasticsearch.py
> +				) as resp:
`				async with self.session().request(
					method="DELETE",
					url=request_url,
					ssl=self.SSLcontext,
					headers=self.Headers,
				) as resp:`

2023-07-11 14:52 UTC, ateska commented
IMPORTANT: I reworked the approach to the SSL configuration.
It is not tested ATM, I'll try to run some basic checks - so take it as the illustration.

2023-07-11 18:28 UTC, ateska commented
Review of extended SSL configuration completed.

2023-07-11 21:29 UTC, ateska requested changes

2023-07-11 21:29 UTC, ateska commented on asab/storage/elasticsearch.py
> +	async def is_connected(self) -> bool:
Why this method is needed?

It is non-systematic - there is no direct connection between the ASAB application and ElasticSearch.

2023-07-11 21:31 UTC, ateska requested changes

2023-07-11 21:31 UTC, ateska commented on examples/storage_elasticsearch.py
> +		connected = await storage.is_connected()
You definitively don't need to wait for anything here.

2023-07-14 07:16 UTC, mejroslav commented
@language-shprt please lint with flake8:
```
asab/storage/elasticsearch.py:1:1: F401 'os' imported but unused
asab/storage/elasticsearch.py:236:1: W293 blank line contains whitespace
asab/storage/elasticsearch.py:559:7: E126 continuation line over-indented for hanging indent
asab/storage/elasticsearch.py:559:20: W291 trailing whitespace
asab/storage/elasticsearch.py:560:21: W291 trailing whitespace
asab/storage/elasticsearch.py:563:7: E123 closing bracket does not match indentation of opening bracket's line
asab/tls.py:30:16: W291 trailing whitespace
```

2023-07-17 14:50 UTC, merged