Exit the app after repeated syslog write failure
TeskaLabs/asab pull request #480
Opened 2023-08-15 10:02 UTC by byewokko

2023-08-25 08:17 UTC, byewokko commented on asab/log.py
> +					sys.exit(1)
it should not exit, use `break` instead

2023-08-25 08:19 UTC, ateska requested changes

2023-08-25 08:19 UTC, ateska commented on asab/log.py
> +		error_counter = 0
Add a comment to `on_write` -> this method is a contingency dump when the socket is not ready.

2023-08-25 08:19 UTC, ateska commented on asab/log.py
> +					sys.exit(1)
No exit - as discussed on the review.

2023-08-25 08:20 UTC, byewokko commented on asab/log.py
> +				if error_counter > 100:
there should not be any counter and exit. simply print the error and the socket error will hopefully fix itself in a bit

2023-08-25 08:21 UTC, byewokko commented on asab/log.py
> +				if error_counter > 100:
also do not `self._enqueue(msg)`
the msg should be thrown away

2023-08-25 13:57 UTC, ateska commented
Don't exit the app - as discussed on review.

2023-08-25 14:39 UTC, byewokko commented on asab/log.py
> +				)
@ateska what should be printed to stderr in this case of socket failure?
- the log message that could not be logged to socket?
- `"Error when writing to syslog ..."` message with details?
- error traceback?

2023-08-26 07:02 UTC, ateska approved these changes

2023-08-28 06:38 UTC, merged