Library documentation improvements
TeskaLabs/asab pull request #531
Opened 2023-12-05 15:08 UTC by mejroslav

Once again I was working with `asab.library` and found some missing info in the documentation.

2023-12-11 21:12 UTC, eliska-n commented
yes! I 100% approve it. A picture. With layers :heart: . But one unresolved question @mithunbharadwaj

2023-12-11 21:13 UTC, eliska-n approved these changes

2023-12-12 07:30 UTC, mithunbharadwaj commented on asab/library/item.py
> +	override: int = 0  # Default value for override is False
The 'override' parameter in the context of a library is an integer value, not a boolean. This parameter specifies the layer level at which the given provider operates.

2023-12-12 10:31 UTC, ateska requested changes

2023-12-12 10:31 UTC, ateska commented on docs/reference/library.md
> +  ![Illustration of Library layers](../images/library/asab-library.drawio.png)
1) The name of the file should be "asab-library-layers.drawio.png"
2) Layers are numbered from 0, with "0" having a special meaning in asap-library micro service

2023-12-12 10:35 UTC, ateska requested changes

2023-12-12 10:35 UTC, ateska commented on asab/library/item.py
> +	override: int = 0  # Default value for override is False
Specify what is a value of "override" for "file1.txt" in the picture below - to add a clarity.

2023-12-12 10:35 UTC, ateska commented on docs/reference/library.md
> +		+ /folder2/folder2.3/
Folders cannot have dots in their names in the library.

2023-12-12 10:35 UTC, ateska commented on docs/reference/library.md
> +	- The item path must end with a file extension (e.g. ".json").
No dots in the folder names.

2023-12-12 10:35 UTC, ateska commented on docs/reference/library.md
> +The library concept supports multi-tenancy. By default, all items of the library are visible for everyone, but you can disable some of them for specific tenants.
Disable & multi-tenancy are two topics (their interconnect here sure).

2023-12-12 10:35 UTC, ateska commented on docs/reference/library.md
> +	- tenant-2
No TABs in YAML.

2023-12-18 09:57 UTC, merged