Draft: add more data to discover services
TeskaLabs/asab pull request #560
Opened 2024-03-19 11:45 UTC by eliska-n

2024-03-19 11:46 UTC, PremyslCerny approved these changes

2024-03-19 13:18 UTC, ateska requested changes

2024-03-19 16:52 UTC, eliska-n commented on asab/api/service.py
> +		res = self.Discovery.update(discovery_dict)
asserts added, that's quite unkind validation, but I think it is valid :upside_down_face:

2024-03-20 21:46 UTC, ateska requested changes

2024-03-20 21:46 UTC, ateska commented on asab/api/service.py
> +	def add_discovery(self, discovery_dict: typing.Dict[str, set]):
This will not be needed.

2024-04-02 08:29 UTC, eliska-n commented
there's no "delete" option. However, the service could update the discovery dict with an empty set. The discovery service/method MUST check for empty sets.

2024-04-02 08:36 UTC, merged