Logging - fix formatting
TeskaLabs/asab pull request #578
Opened 2024-06-03 12:36 UTC by eliska-n

continues on this branch: https://github.com/TeskaLabs/asab/pull/576

The biggest disadvantage is the `copy()` mechanism used. It does not work without it.

If merged, we could start sing colors in docker again :)

2024-06-19 12:19 UTC, eliska-n commented
not yet fully tested, I'll come back to this one ASAP

2024-06-26 09:48 UTC, ateska approved these changes

2024-07-04 16:23 UTC, eliska-n commented
@ateska I'm reviving this MR

There's a _loop_exception_handler method in the log.py that is unused. I'd like to delte it, but it has quite nice docstring looking important

2024-07-04 17:06 UTC, eliska-n commented
don't know what is sd_id and what it is good for

2024-07-04 17:09 UTC, eliska-n commented
I forgot what I did with the formatting in the structured data formatter

2024-07-04 17:12 UTC, eliska-n commented on asab/log.py
> +	INSTANCE_ID = os.environ.get("INSTANCE_ID")
this is crucial for analysis of the data. it should be added to the log in other formatters, too. OR why not to have it in a logger (i.e. BEFORE it gets to formatting)

2024-07-04 17:13 UTC, eliska-n commented on asab/log.py
> +						self.SyslogHandler.setFormatter(JSONFormatter())
json format is configured in [logging:syslog] config section. But it is not a syslog, isn't it? What is it?

2024-07-04 17:24 UTC, eliska-n commented
For the formatting only - the aim is to have colorful logs in console and not colorful in logs sent... somewhere...
That should be possible now - because the formatters do not influence each other (because they don't modify the record).

So, I'll delete the "running_in_container" check and let's see what happens

2024-07-04 17:37 UTC, ateska requested changes

2024-07-04 17:37 UTC, ateska commented on asab/log.py
> +	HOSTNAME = socket.gethostname()
`INSTANCE_ID` etc. is not mandatory ..

2024-07-04 17:41 UTC, eliska-n commented
Tests needed:

- [ ] in development
- [ ] in docker container
- [ ] in our UI (Maintenance > Services >> terminal
- [ ] in syslog
- [ ] in json

2024-07-04 17:54 UTC, eliska-n commented on asab/log.py
> +						self.SyslogHandler.setFormatter(JSONFormatter())
that's ok

2024-07-04 17:54 UTC, eliska-n commented on asab/log.py
> +	INSTANCE_ID = os.environ.get("INSTANCE_ID")
nope, we dont want to have the ids in console

2024-07-15 10:23 UTC, merged